name: 'Rebol-Speak CI'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.17.0

    - name: Build 32bit Rebol/Speak extension
      run: ./siskin Rebol-Speak.nest --msvc -o ./speak-windows-x86.rebx speak-x86

    - name: Build 64bit Rebol/Speak extension
      run: ./siskin Rebol-Speak.nest --msvc -o ./speak-windows-x64.rebx speak-x64

    - name: Install Rebol for extension test
      uses: oldes/install-rebol@v3.18.0

    - name: Minimal Rebol/Speak extension test
      run:  ./rebol3 ci-test.r3

    - uses: actions/upload-artifact@v3
      with:
        name: Rebol-Speak-CI-${{github.run_id}}
        path: ./*.rebx

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.17.0

    - name: Build 64bit Rebol Blend2d extension (Intel)
      run: ./siskin Rebol-Speak.nest -o ./speak-macos-x64.rebx speak-x64

    - name: Build 64bit Rebol Blend2d extension (ARM)
      run: ./siskin Rebol-Speak.nest -o ./speak-macos-arm64.rebx speak-arm64

    - name: Install Rebol for extension test
      uses: oldes/install-rebol@v3.18.0

    - name: Minimal Rebol/Speak extension test
      run:  ./rebol3 ci-test.r3

    - name: Compress 64bit Rebol Blend2d extension
      run:  |
        gzip -9 ./speak-macos-x64.rebx
        gzip -9 ./speak-macos-arm64.rebx

    ###############################################################################
    # Collecting build artifacts...
    - uses: actions/upload-artifact@v3
      with:
        name: Rebol-Speak-CI-${{github.run_id}}
        path: ./*.rebx.gz

