name: 'Rebol-Speak CI'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.17.0

    - name: Build 32bit Rebol/Speak extension
      run: ./siskin Rebol-Speak.nest --msvc -o ./speak-windows-x86.rebx speak-windows-x86.rebx

    - name: Build 64bit Rebol/Speak extension
      run: ./siskin Rebol-Speak.nest --msvc -o ./speak-windows-x64.rebx speak-windows-x64.rebx

    - name: Install Rebol for extension test
      uses: oldes/install-rebol@v3.18.0
      with:
        product: Bulk

    - name: Minimal Rebol/Speak extension test
      run:  ./rebol3 ci-test.r3

    - uses: actions/upload-artifact@v3
      with:
        name: Rebol-Speak-CI-${{github.run_id}}
        path: ./*.rebx

